project_id = "zwgjbffesalpiaaycbac"

[functions.paystack-webhook]
verify_jwt = false

[functions.smile-id-webhook]
verify_jwt = false

[functions.sitemap-xml]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
